### PR TITLE
Clean up, new features

### PR DESCRIPTION
**Pull request by karasikov**
Fixed the README file, added iterators to the elements cached and callback for elements erased

### CODE REVIEW

**Comment by karasikov** [comment]
Hi Vladimir,

- I am using the class to cache objects that are compressed by default (Get() here returns me pointers to their uncompressed temporary copies).
Therefore, after erasing an uncompressed object from the cache, it is crucial to compress that object and synchronize it with the others.
I decided the OnErase callback would do that. Please let me know if you have another solution for that purpose in mind.

- I switched lru_iterator to non-const iterator to avoid some compilation warnings in splice(...). So that now it compiles without warnings on all gcc versions tested.

Thanks for your nice library!

**Comment by vpetrigo** [comment]
Hello Mikhail,

Sorry for delay with responses.
I would rather introduce another set of methods that utilizes a callback provided in the constructor. I just imagined that there might be cases when someone does not want a callback to be called.
Would you tell if that makes sense for you?

Also related to your last commit I am not sure that calling a callback function in `Clear()` method is necessary as we call the same callback with the same arguments.

**Comment by karasikov** [comment]
Hi Vladimir,

> I would rather introduce another set of methods that utilizes a callback provided in the constructor.

Since OnEraseCallback is called when an element is being erased from fixed_sized_cache, and this is actually hidden from a user, I don't really see how this could be implemented.

> I just imagined that there might be cases when someone does not want a callback to be called.
> Would you tell if that makes sense for you?

Could you try to make up an example?

> Also related to your last commit I am not sure that calling a callback function in Clear() method is necessary as we call the same callback with the same arguments.

In fixed_sized_cache::Clear(), OnEraseCallback is called now exactly once for each element cached.
Note that we call Policy::Erase but not fixed_sized_cache::Erase there, and Policy::Erase does not run the callback.

In my opinion, the current version is fine. By default, no callback is called, but there is also an option to provide one to deinitialize the objects that have been cached.

**Comment by vpetrigo** [comment]
> In my opinion, the current version is fine. By default, no callback is called, but there is also an option to provide one to deinitialize the objects that have been cached.
Ok, let's merge that one and after that think about improvments. :)

**Pull request merged**
